FROM golang:latest
WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh \    
&& chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air

COPY pkg/ pkg/
COPY main.go ./
COPY .air.toml ./
RUN go mod download

ENTRYPOINT [ "air" ]